<template lang="html">
  <sui-container>
    <sui-table inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="red" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="orange" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="yellow" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="olive" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="green" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="teal" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="blue" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="violet" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="purple" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="pink" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="grey" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
    <sui-table color="black" inverted>
      <sui-table-header>
        <sui-table-row>
          <sui-table-header-cell>Food</sui-table-header-cell>
          <sui-table-header-cell>Calories</sui-table-header-cell>
          <sui-table-header-cell>Protein</sui-table-header-cell>
        </sui-table-row>
      </sui-table-header>
      <sui-table-body>
        <sui-table-row>
          <sui-table-cell>Apples</sui-table-cell>
          <sui-table-cell>200</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
        <sui-table-row>
          <sui-table-cell>Orange</sui-table-cell>
          <sui-table-cell>310</sui-table-cell>
          <sui-table-cell>0g</sui-table-cell>
        </sui-table-row>
      </sui-table-body>
    </sui-table>
  </sui-container>
</template>

<script>
export default {
  name: 'TableColoredExample',
};
</script>
